services:
  - type: web
    name: ar-west-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: AR_TRACKER_API_KEY
        value: arwest-cf-2026-internal
      - key: PYTHON_VERSION
        value: "3.11.0"
